"""Vessel Tracking API Python SDK.

Usage::

    from vessel_api_python import VesselClient

    client = VesselClient(api_key="your-api-key")
    result = client.search.vessels(filter_name="Ever Given")
"""

from ._client import AsyncVesselClient, VesselClient
from ._constants import DEFAULT_BASE_URL, VERSION
from ._errors import (
    VesselAPIError,
    VesselAuthError,
    VesselNotFoundError,
    VesselRateLimitError,
    VesselServerError,
)
from ._iterator import AsyncIterator, SyncIterator
from ._models import (
    MODU,
    BroadcastStation,
    Classification,
    ClassificationCertificate,
    ClassificationCondition,
    ClassificationDimensions,
    ClassificationHull,
    ClassificationIdentification,
    ClassificationInfo,
    ClassificationMachinery,
    ClassificationOwner,
    ClassificationPurpose,
    ClassificationResponse,
    ClassificationSurvey,
    ClassificationVessel,
    ClassificationYard,
    DGPSStation,
    DGPSStationsWithinLocationResponse,
    FindDGPSStationsResponse,
    FindLightAidsResponse,
    FindMODUsResponse,
    FindPortsResponse,
    FindRadioBeaconsResponse,
    FindVesselsResponse,
    GeoJSON,
    Inspection,
    InspectionDeficiency,
    InspectionDetail,
    InspectionDetailRecord,
    InspectionDetailResponseData,
    InspectionRecord,
    InspectionsResponseData,
    LightAid,
    LightAidsWithinLocationResponse,
    MarineCasualtiesResponse,
    MarineCasualty,
    MODUsWithinLocationResponse,
    Navtex,
    NavtexMessagesResponse,
    Ownership,
    OwnershipResponseData,
    Port,
    PortCountry,
    PortEvent,
    PortEventResponse,
    PortEventsResponse,
    PortReference,
    PortResponse,
    PortsWithinLocationResponse,
    RadioBeacon,
    RadioBeaconsWithinLocationResponse,
    TypesInspectionDetailResponse,
    TypesInspectionsResponse,
    TypesOwnershipResponse,
    Vessel,
    VesselEmission,
    VesselEmissionsResponse,
    VesselETA,
    VesselETAResponse,
    VesselFormerName,
    VesselOwnership,
    VesselPosition,
    VesselPositionResponse,
    VesselPositionsResponse,
    VesselReference,
    VesselResponse,
    VesselsWithinLocationResponse,
)

__all__ = [
    # Clients
    "VesselClient",
    "AsyncVesselClient",
    # Errors
    "VesselAPIError",
    "VesselAuthError",
    "VesselNotFoundError",
    "VesselRateLimitError",
    "VesselServerError",
    # Iterators
    "SyncIterator",
    "AsyncIterator",
    # Constants
    "VERSION",
    "DEFAULT_BASE_URL",
    # Models — Shared / helper
    "GeoJSON",
    "PortCountry",
    "PortReference",
    "VesselReference",
    "VesselFormerName",
    "BroadcastStation",
    # Models — Classification sub-models
    "ClassificationCertificate",
    "ClassificationCondition",
    "ClassificationDimensions",
    "ClassificationHull",
    "ClassificationIdentification",
    "ClassificationInfo",
    "ClassificationMachinery",
    "ClassificationOwner",
    "ClassificationPurpose",
    "ClassificationSurvey",
    "ClassificationVessel",
    "ClassificationYard",
    # Models — Vessel
    "Vessel",
    "VesselResponse",
    "VesselPosition",
    "VesselPositionResponse",
    "VesselPositionsResponse",
    "MarineCasualty",
    "MarineCasualtiesResponse",
    "Classification",
    "ClassificationResponse",
    "VesselEmission",
    "VesselEmissionsResponse",
    "VesselETA",
    "VesselETAResponse",
    # Models — Inspection
    "InspectionRecord",
    "Inspection",
    "InspectionDeficiency",
    "InspectionDetailRecord",
    "InspectionDetail",
    "InspectionsResponseData",
    "InspectionDetailResponseData",
    "TypesInspectionsResponse",
    "TypesInspectionDetailResponse",
    # Models — Ownership
    "VesselOwnership",
    "Ownership",
    "OwnershipResponseData",
    "TypesOwnershipResponse",
    # Models — Port
    "Port",
    "PortResponse",
    "PortEvent",
    "PortEventResponse",
    "PortEventsResponse",
    # Models — Search
    "FindVesselsResponse",
    "FindPortsResponse",
    "DGPSStation",
    "FindDGPSStationsResponse",
    "LightAid",
    "FindLightAidsResponse",
    "MODU",
    "FindMODUsResponse",
    "RadioBeacon",
    "FindRadioBeaconsResponse",
    # Models — Location
    "VesselsWithinLocationResponse",
    "PortsWithinLocationResponse",
    "DGPSStationsWithinLocationResponse",
    "LightAidsWithinLocationResponse",
    "MODUsWithinLocationResponse",
    "RadioBeaconsWithinLocationResponse",
    # Models — Navtex
    "Navtex",
    "NavtexMessagesResponse",
]
